config/routes.rb
Rails.application.routes.draw do

  resources :associates

  resources "contacts", only: [:new, :create]

  resources :consultants

  get 'comments/create'

  get 'comments/destroy'

  resources :posts, :path => 'blog' do
    resources :comments
  end

  get 'whatwedo/starter'

  get 'whatwedo/agrinvest'

  get 'whatwedo/organic'

  get 'whatwedo/government'

  get 'careers/associate'

  get 'careers/independent'

  get 'whatwedo/social'

  get 'whatwedo/consulting'

  get 'whatwedo/technology'

  get 'home/index'

  get 'aboutus' => "home#aboutus"

  get 'whatwedo' => "home#whatwedo"

  get 'careers' => "home#careers"

  get 'starter' => "home#starter"

  get 'agrinvest' => "home#agrinvest"

  get 'gaae' => "home#gaae"

  get 'organic' => "home#organic"

  get 'privacy' => "home#privacy"

  get 'terms' => "home#terms"

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def aboutus
  end

  def whatwedo
  end

  def careers
  end

  def starter
  end

  def agrinvest
  end

  def gaae
  end

  def organic
  end

  def blog
  end

  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/blog.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3>Our Blog </h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>
<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"4></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>

         <div class="container">
           <center>
               <h3 class="design">Rendzina Blog <br/><i class="fa fa-arrow-circle-o-down"></i></h3>
               <hr/>
               <h2 style="color: #ccc"> Under Construction </h2>
           </center>

        </div>


    </div>
</section>


<section class="testimonies-section">

    <div class="container designer" >
          <div style="margin:50px auto;" class="container">
         <center>
             <h3 class="Google-font"> Twitter Tweet </h3>
        </center>
             <p class="justify">

              &nbsp;

             </p>

          </div>
     </div>
</section>

app/views/home/careers.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3> Careers </h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
        <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">

                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>

<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>


         <div class="container">
           <center>
               <h3 class="design">Rendzina Careers <br/><i class="fa fa-arrow-circle-o-down"></i></h3>
               <hr/>
					</center>
               <p>
								 	<p>If you are looking for an organization that will value, recognize and reward talent and results, if you want to help find solutions to enterprise and entrepreneurship challenges and of course you want to have fun and keep learning along the way, then Rendzina is the place to be.</p>

							 	<p>At Rendzina, we offer opportunities for qualified people to work with us in 2 categories.</p>
							</p>

				      <center>
								<%= link_to new_associate_path, class: "btn btn-primary btn-sm" do %>
								  <b><i class="fa fa-plus"></i> Become an Associate </b>
                 <% end %>

                 <%= link_to new_consultant_path, class: "btn btn-success btn-sm" do %>
 								  <b><i class="fa fa-plus"></i> Join as an Independent Consultant </b>
                  <% end %>

							</center>
        </div>

				<br/>


    </div>
</section>


<section class="testimonies-section">

    <div class="container designer" >
          <div style="margin:50px auto;" class="container">
         <center>
             <h3 class="Google-font"> Why Rendzina ? </h3>
        </center>
        <p class="justify">

         <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
         <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

        </p>

          </div>
     </div>
</section>

app/views/home/index.html.erb
<section class="slider-section">
     <div style="margin:auto;position:absolute;z-index: 1000;width: 100%">

        <div class="inner-text animated flipInX">
            <h3> Welcome to Rendzina </h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
          <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
          <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
     <container>
			<slide style="background-image: url('assets/Broad-bean-seedlings-in-a-014.jpg')"><span>&nbsp; </span></slide>
			<slide style="background-image: url('assets/blackpeoplenetworking.jpg')"><span>&nbsp;</span></slide>
			<slide style="background-image: url('assets/cape-consulting.jpg')"><span>&nbsp; </span></slide>
			<slide style="background-image: url('assets/about_banner.jpg')"><span>&nbsp;</span></slide>
      
			<div class="next">&rtrif;</div>
			<div class="prev">&ltrif;</div>
		</container>
		<script>
      $(function(){
  			$('container').pureSlider({
  				slideNode: 'slide'
  			});
     });
		</script>

</section>

<section class="content-section">

   <div class="container">

   </div>

    <div >
            <div class="real-time-contact">
              <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
              <%= link_to root_path, class: 'send_enq' do %>
                 <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
              <% end %>
            </div>
            <div class="container center" style="width: 50%;">
              <br/><br/>
              <p>
            In today’s world, Enterprises, Entrepreneurs and Governments are in dire need of Strategic and Proactive systems to growth and development and Rendzina LTD is here to fill that need.
          </p>
            <p>
Rendzina LTD creates effective Management and Technology solutions that help organizations improve productivity.
We are an Enterprise Development Consulting Company helping clients develop their businesses with tools in Management Consulting and Technology applications.
</p>
      </div>
        </div>
        <div class="rows container">
           <div class="col-md-4">

               <div class="circle-image">
                  <%= link_to whatwedo_starter_path do %>
                  <%= image_tag "business_starter", width:"100%" %>
                  <% end %>
               </div>
               <h4 class="design center"> Business Starter </h4>
               <p class="center">
                 At Rendzina Capital we are committed to rendering services that make the pursuit of
    business as less stressful as possible. To fulfill this aim of ours we choose to ease the burden
    of getting a business started by providing various categories of our Business starter
    packages.
                   <br/>
                   <%= link_to whatwedo_starter_path, class: "btn btn-danger btn-sm" do %>
                      view more <i class="fa fa-arrow-circle-right"></i>
                   <% end %>
               </p>

           </div>

           <div class="col-md-4">
             <div class="circle-image">
                <%= link_to(whatwedo_agrinvest_path) do %>
                <%= image_tag "agrinvest", width:"100%" %>
                <% end %>
             </div>
             <h4 class="design center"> Agrinvest </h4>
             <p class="center">
                Agrinvest is an agricultural investment and development solution designed to foster agro-preneurship (Agricultural Entrepreneurship) and develop opportunities in the agricultural sector into sustainable and competitive enterprises.
                <br/>
                <%= link_to whatwedo_agrinvest_path, class: "btn btn-warning btn-sm" do %>
                   view more <i class="fa fa-arrow-circle-right"></i>
                <% end %>
             </p>
           </div>

           <div class="col-md-4">

             <div class="circle-image">
                <%= link_to whatwedo_organic_path do %>
                <%= image_tag "organic_plan", width:"100%" %>
                <% end %>
             </div>
              <h4 class="design center"> Organic Business Plan </h4>
              <p class="center">

                              The concept of Business Plan writing at Rendzina Capital is one which has evolved over the years into an
                organic piece of organizational Strategy that allows entrepreneurs and their organizations make
                informed decisions while adapting to changes along the way.<br/>
                 <%= link_to whatwedo_organic_path, class: "btn btn-success btn-sm" do %>
                    view more <i class="fa fa-arrow-circle-right"></i>
                 <% end %>
              </p>

           </div>

           <div class="clearfix">
           </div>



        </div>
    </div>
</section>

<section class="mission-style">
  <div class="transparent">
  <div class="container">
          <center>
              <h3 class="design"> Why Rendzina ? <br/><i class="fa fa-arrow-circle-down"></i></h3>
              <hr/>
          </center>

          <p class="justify">

           <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
           <p>
 Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
 <p>
 At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
 <p>
 We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
 </p>

          </p>
      </div>
    </div>
</section>

<section class="testimonies-style1">
  <div class="col-md-6 col-md-offset-3">
          <center>
              <h3 class="design"> Testimonies <br/><i class="fa fa-arrow-circle-down"></i></h3>
              <hr/>
          </center>

          <p class="center">

Rendzina Capital is that organization of intrinsic excellence, committed people with a positive and learning culture springing up superior Socio-Management Services and IT Solutions that foster growth and stability for all business people.<br/>
  <b>John Doe</b><br/>
   <a href="#"> <i class="fa fa-arrow-circle-left"></i></a> &nbsp;    <a href="#"> <i class="fa fa-arrow-circle-right"></i></a>
 </p>
      </div>

</section>


<section class="testimonies-section">

    <div class="container designer" >
          <div style="width: 100%; max-width: 600px;margin:50px auto;">
         <center>
             <h3 class="Google-font"> Resources </h3>
             <p>
               Our bank of resources is an archive of insightful articles that does more than inform but revolutionize our thinking processes.

 Here we place in your hands, the power of knowledge with which you can transform your personal life and business.

              <br/> <br/>
              <%= link_to 'blog', class: "btn btn-success btn-lg" do %>
                <b><i class="fa fa-comments"></i> View Our Blog </b>
               <% end %>
             </p>
         </center>
          </div>
     </div>
</section>

app/views/home/whatwedo.html.erb
<%# link = 'about' %>
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3> What we do </h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
        <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>

<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>


         <div class="container">
           <center>
               <h3 class="design">Our Work  <br/><i class="fa fa-arrow-circle-down"></i></h3>
               <hr/>
           </center>
           <p class="justify">
             <p>Rendzina LTD is an enterprise development consulting company whose mission is set on working with entrepreneurs, organizations and governments to solve complex problems, improve performance, drive critical change and maximize value for all stakeholders. </p>

           	<p>We are aware that the process of the transformation of goals, ideas and strategic aspirations in business is no easy task. To succeed in today's environment, businesses and governments need to lead through increased complexity and volatility, drive operational excellence and engage collaboration across enterprise functions and we are here to help them do so profitably.</p>

           	<p>At Rendzina, we integrate management consulting expertise with the science of enterprise development to arrive at a bouquet of solutions filtered into <%= link_to "Social Networking",  whatwedo_social_path, class: "color-brown" %>, <%= link_to "Consulting & Technology", whatwedo_consulting_path, class: "color-green" %>.</p>

           	<p>Leveraging on our diverse functional expertise, we offer all our business clients a wide range of services to support critical aspects of their business.</p>


        </div>


        <div class="rows container links">
           <div class="col-md-4">
             <%= link_to whatwedo_social_path do %>
                 <div class="circle-image">
                    <%= image_tag "networking", width:"100%", style:"height: 100%" %>
                 </div>
                 <h4 class="design center"> Networking </h4>
               <% end %>
               <p class="center">
                 The Rendzina LTD has as one of its principal functions the art of creating networking events that help entrepreneurs increase their businesses through structured..
               </p>
               <center>
                 <%= link_to whatwedo_social_path, class: "btn btn-warning btn-sm" do %>
                 Read More <i class="fa fa-arrow-circle-right"></i>
               <% end %>
             </center>
           </div>

           <div class="col-md-4">
             <%= link_to whatwedo_consulting_path do %>
                 <div class="circle-image">
                    <%= image_tag "IMG-20160510-WA0002", width:"100%", style:"height:100%" %>
                 </div>
                 <h4 class="design center"> Consulting </h4>
             <% end %>
             <p class="center">
               Today's entrepreneur is faced with multiple challenges caused by globalization, competition, diversification, emerging trends, commercialization etc.The need for specialized knowledge and systematic assistance is on the increase in the business world for companies whether great or small to be effective and remain competitive.
             </p>
             <center>
               <%= link_to whatwedo_consulting_path, class: "btn btn-primary btn-sm" do %>
               Read More <i class="fa fa-arrow-circle-right"></i>
             <% end %>
           </center>
           </div>

           <div class="col-md-4">
             <%= link_to whatwedo_technology_path do %>
               <div class="circle-image">
                  <%= image_tag "IMG-20160510-WA0005", width:"100%", style: "height: 100%" %>
               </div>
                <h4 class="design center"> Technology </h4>
            <% end %>
            <p class="center">
              Every company’s technology apparatus should support its business strategy and not constrain it. We have our focus first on the strategic needs of our client’s businesses to determine the technology capabilities needed to support their long-term goals.
            </p>
            <center>
              <%= link_to whatwedo_technology_path, class: "btn btn-success btn-sm" do %>
              Read More <i class="fa fa-arrow-circle-right"></i>
            <% end %>
          </center>
           </div>

           <div class="clearfix"></div>
        </div>


        <%# -- This is the new section for other services %>

        <div class="rows container links">

           <div class="col-md-4">
             <%= link_to whatwedo_government_path do %>
               <div class="circle-image">
                  <%= image_tag "government", width:"100%" %>
               </div>
                <h4 class="design center"> Governance As An Enterprise  </h4>
            <% end %>
            <p class="center">
               Today’s service-based economy is fundamentally dependent on IT. Through these computer-based systems, the critical interactions at the heart of service delivery are defined, managed, recorded, and governed. Furthermore, in recent years...
            </p>
            <center>
              <%= link_to whatwedo_technology_path, class: "btn btn-success btn-sm" do %>
              Read More <i class="fa fa-arrow-circle-right"></i>
            <% end %>
          </center>
           </div>


           <div class="col-md-4">
             <%= link_to '#' do %>
                 <div class="circle-image">
                    <%= image_tag "our_people", width:"100%" %>
                 </div>
                 <h4 class="design center"> R.E.M.S </h4>
             <% end %>
           </div>

           <div class="col-md-4">
             <%= link_to root_path do %>
               <div class="circle-image">
                  <%= image_tag "IMG-20160510-WA0004", width:"100%", style: "height: 100%" %>
               </div>
                <h4 class="design center"> Digital Revolution </h4>
            <% end %>
           </div>

           <div class="clearfix"></div>
        </div>
    </div>
</section>


<section class="testimonies-section">

    <div class="container designer" >
          <div style="margin:50px auto;" class="container">
         <center>
             <h3 class="Google-font"> Why Rendzina ? </h3>
        </center>
             <p class="justify">

              <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
              <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

             </p>

          </div>
     </div>
</section>