config/routes.rb
Rails.application.routes.draw do

  resources :associates

  resources "contacts", only: [:new, :create]

  resources :consultants

  get 'comments/create'

  get 'comments/destroy'

  resources :posts, :path => 'blog' do
    resources :comments
  end

  get 'whatwedo/starter'

  get 'whatwedo/agrinvest'

  get 'whatwedo/organic'

  get 'whatwedo/government'

  get 'careers/associate'

  get 'careers/independent'

  get 'whatwedo/social'

  get 'whatwedo/consulting'

  get 'whatwedo/technology'

  get 'home/index'

  get 'aboutus' => "home#aboutus"

  get 'whatwedo' => "home#whatwedo"

  get 'careers' => "home#careers"

  get 'starter' => "home#starter"

  get 'agrinvest' => "home#agrinvest"

  get 'gaae' => "home#gaae"

  get 'organic' => "home#organic"

  get 'privacy' => "home#privacy"

  get 'terms' => "home#terms"

  root 'home#index'

end

app/models/associate.rb
class Associate < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
end

app/models/consultant.rb
class Consultant < ActiveRecord::Base
end

app/models/independent_consultant.rb
class IndependentConsultant < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	has_attached_file :avatar, styles: { medium: "300x300>", show: "500x500>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	has_attached_file :author, styles: { thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :author, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  before_action :set_associate, only: [:show, :edit, :update, :destroy]

  # GET /associates
  # GET /associates.json
  def index
    @associates = Associate.all
  end

  # GET /associates/1
  # GET /associates/1.json
  def show
  end

  # GET /associates/new
  def new
    @associate = Associate.new
  end

  # GET /associates/1/edit
  def edit
  end

  # POST /associates
  # POST /associates.json
  def create
    @associate = Associate.new(associate_params)

    respond_to do |format|
      if @associate.save
        format.html { redirect_to root_path, notice: 'Associate was successfully created.' }
        format.json { render :show, status: :created, location: @associate }
      else
        format.html { render :new }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associates/1
  # PATCH/PUT /associates/1.json
  def update
    respond_to do |format|
      if @associate.update(associate_params)
        format.html { redirect_to root_path, notice: 'Associate was successfully updated.' }
        format.json { render :show, status: :ok, location: @associate }
      else
        format.html { render :edit }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associates/1
  # DELETE /associates/1.json
  def destroy
    @associate.destroy
    respond_to do |format|
      format.html { redirect_to associates_url, notice: 'Associate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associate
      @associate = Associate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associate_params
      params.require(:associate).permit(:surname, :other_names, :dob, :contact_add, :sec_institution, :sec_certificate, :sec_date, :uni_institution, :uni_certificate, :uni_date, :other_institution, :other_certificate, :other_date, :personal_statement, :hobbies, :telephone, :email)
    end
end

app/controllers/careers_controller.rb
class CareersController < ApplicationController
  def associate
  end

  def independent
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(comment_params)
  	@comment.save

  	redirect_to posts_url, notice: 'Comment was successfully created.'
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

  	redirect_to @comment.post
  end

  private

  def comment_params
  	params.require(:comment).permit(:comment)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def aboutus
  end

  def whatwedo
  end

  def careers
  end

  def starter
  end

  def agrinvest
  end

  def gaae
  end

  def organic
  end

  def blog
  end

  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "rendzina", password: "Rendz1na", only: :new
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :message, :avatar, :author, :author_name)
    end
end

app/controllers/whatwedo_controller.rb
class WhatwedoController < ApplicationController
  def social
  end

  def consulting
  end

  def technology
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/helpers/careers_helper.rb
module CareersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/consultants_helper.rb
module ConsultantsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/whatwedo_helper.rb
module WhatwedoHelper
end

app/views/contact_us/contacts/new.html.erb
<h2><%= t('.contact_us') %></h2>
<%= form_for @contact, :url => contacts_path, :html => {:class => 'formtastic'} do |f| %>
  <% if ContactUs.require_name %>
    <div class='string required' id='contact_us_contact_name_input'>
      <%= f.label :name, (t('.name') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :name %>
      <% if f.object.errors[:name].present? %>
        <p class='inline-error'><%= f.object.errors[:name].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='string required' id='contact_us_contact_email_input'>
    <%= f.label :email, (t('.email') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_field :email %>
    <% if f.object.errors[:email].present? %>
      <p class='inline-error'><%= f.object.errors[:email].join(' and ') %></p>
    <% end %>
  </div>
  <% if ContactUs.require_subject %>
    <div class='string required' id='contact_us_contact_subject_input'>
      <%= f.label :subject, (t('.subject') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
      <%= f.text_field :subject %>
      <% if f.object.errors[:subject].present? %>
        <p class='inline-error'><%= f.object.errors[:subject].join(' and ') %></p>
      <% end %>
    </div>
  <% end %>
  <div class='text required' id='contact_us_contact_message_input'>
    <%= f.label :message, (t('.message') + content_tag(:abbr, '*', :class => 'required')).html_safe %>
    <%= f.text_area :message %>
    <% if f.object.errors[:message].present? %>
      <p class='inline-error'><%= f.object.errors[:message].join(' and ') %></p>
    <% end %>
  </div>
  <div class='commit'>
    <%= f.submit :submit, :class => 'submit create', :title => t('.submit') %>
  </div>
<% end %>

app/views/contact_us/contacts/new_formtastic.html.erb
<h2><%= t('.contact_us') %></h2>
<%= semantic_form_for @contact, :url => contacts_path do |f| %>
  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
  <%= f.input :email, :label => t('.email') %>
  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
  <%= f.input :message, :as => :text, :label => t('.message') %>
  <%= f.action :submit, :label => t('.submit'), :button_html => { :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') } %>
<% end %>

app/views/contact_us/contacts/new_simple_form.html.erb
<div class="row" style="margin-top:2em;">
	<h2><%= t('.contact_us') %></h2>
	<%= simple_form_for @contact, :url => contacts_path do |f| %>
	  <%= f.input :name, :label => t('.name') if ContactUs.require_name %>
	  <%= f.input :email, :label => t('.email') %>
	  <%= f.input :subject, :label => t('.subject') if ContactUs.require_subject %>
	  <%= f.input :message, :as => :text, :label => t('.message') %>
	  <%= f.button :submit, :value => t('.submit'), :alt => t('.submit'), :id => 'contact_us_contact_submit', :title => t('.submit') %>
	<% end %>

</div>

app/views/layouts/_footer.html.erb
    <div class="container">
      
        <div class="col-md-4">

            <ul class="footer-links">
                <li>
                    <b> Company </b>
                </li>

                <li>
                    <a href="<%= aboutus_path %>"> About Us </a>
                </li>
                <li>
                    <a href="blog"> Our Blog </a>
                </li>
                <li>
                   <a href="<%= terms_path %>"> Terms of Use</a>
               </li>
                <li>
                    <a href="<%= privacy_path %>"> Privacy Policy</a>
                </li>


            </ul>
        </div>

        <div class="col-md-4">

            <ul class="footer-links">
                <li>
                    <b>Careers </b>
                </li>
                <li>
                    <a href="#"> Vacancies </a>
                </li>
                <li>
                    <a href="<%= new_associate_path %>"> Associate </a>
                </li>
                <li>
                    <a href="<%= new_consultant_path %>"> Independent Consultant</a>
                </li>
                <li>
                    <a href="#"> Contact Us </a>
                </li>

            </ul>
        </div>

        <div class="col-md-4">

            <ul class="footer-links">
                <li>
                    <b> <i class="fa fa-info-circle"></i> Contact Us </b>
                </li>
                <div>

                  <p class="office-address">
                    <b> Office Address </b>
                    <br/>
                     25, Oduduwa way,<br/>
                     GRA, Ikeja,<br/>
                     Lagos.<br/>
                     <a href="#"><small><b> Send enquiry </b></small></a>
                  </p>

                    <form class="contact-form" style="display:none">
                        <div class="col-md-6">
                          <label> Full Name </label>
                          <input type="text" class="form-control" name="fname"/>
                        </div>
                        <div class="col-md-6">
                          <label> Email Address </label>
                          <input type="text" class="form-control" name="email" />
                        </div>
                        <div class="clearfix"></div>
                        <div class="col-md-12">
                        <label> Content </label>
                        <textarea class="form-control" name="content"></textarea>
                        <br/>
                        <a href="#" class="hide-me"><small> Hide enquiry </small></a>
                        <button class="btn btn-success btn-sm pull-right"><i class="fa fa-send-o"></i> Send</button>

                        </div>
                    </form>
                </div>

            </ul>

        </div>

        <div class="clearfix"></div>
    </div>

    <div class="bg-color-black">

        <center>
            <small><b class="base-footer"> Powered By Rendzina LTD <%= Date.today.year %> </b></small>
        </center>
    </div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>

<!DOCTYPE HTML>
<html> 
    <head>
        <title> Welcome to Official Website of Rendzina </title>
        
   
        <?php
          //print link_tag('css/vendor/bootstrap.min.css');
          print link_tag('css/vendor/bootstrap.min.css');
          print link_tag('css/vendor/bootflat.min.css');
          print link_tag('css/vendor/font-awesome.min.css');
          print link_tag('css/vendor/animate.css');
          print link_tag('css/vendor/css/styles.css');
          
        ?>
        
       <script src="scripts/jquery.1.11.js"></script>
          <script src="scripts/pureSlider.js"></script>
    </head>    
    <body>
        
    

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% page = request.path.to_s %>
<%# page %>
<div style="background: yellowgreen;padding: 2px;height: 2px;">&nbsp;</div>
<section class="header-section">

  <div class="container">
   <div class="col-md-3">

         <%= link_to image_tag("our_logo1"), root_path%>

   </div>
   <div class="col-md-8">

       <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="margin-top:1.2em;">
      <ul class="nav navbar-nav">
          <li
             <% if page === '/' %>
              class="active"
             <% end %>>
            <!--<a href="#">Home </a>-->
						<%= link_to 'Home', root_path %>

        </li>
        <li <% if page === '/aboutus' %>
           class="active"
        <% end %>>
            <!--<a href="#"> About </a>-->
						<%= link_to 'About', aboutus_path %>

        </li>

         <li <% if page === '/whatwedo' || page === '/whatwedo/consulting' || page === '/whatwedo/technology' || page === '/whatwedo/social' || page === '/whatwedo/agrinvest' %>
         class="active"
         <% end %>>
            <!--<a href="#">What we do</a> -->
            <%= link_to 'What We Do', whatwedo_path %>
        </li>

        <li <% if page == '/blog' %>
           class="active"
        <% end %>>
            <!--<a href="#"> Blog </a>-->
            <%= link_to 'Blog', posts_path %>
        </li>
        <li <% if page === '/careers' || page ==='/careers/associate' || page === '/careers/independent' %>
          class="active"
        <% end %>>
            <!--<a href="#"> Careers </a>-->
            <%= link_to 'Careers', careers_path %>
        </li>
<!--           <li >
            <a href="#"> Contacts </a>
        </li> -->

      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
   </div>

    <div class="clearfix"></div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>
    <head>
        <title><%= content_for?(:title) ? yield(:title) : "Rendzina" %></title>
        <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rendzina" %>">
        <%# This is the CSS files %>
        <%= stylesheet_link_tag "vendor/bootstrap.min" %>
        <%= stylesheet_link_tag "vendor/bootflat.min" %>
        <%= stylesheet_link_tag "vendor/font-awesome.min" %>
        <%= stylesheet_link_tag "vendor/animate" %>
        <%= stylesheet_link_tag "vendor/css/styles" %>
        <%= stylesheet_link_tag "slider" %>
        <%# Javascript Files %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>
        <script>
          (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
          (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
          m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
          })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

          ga('create', 'UA-77194406-1', 'auto');
          ga('send', 'pageview');

        </script>
        <!-- Facebook Pixel Code -->
        <script>
        !function(f,b,e,v,n,t,s){if(f.fbq)return;n=f.fbq=function(){n.callMethod?
        n.callMethod.apply(n,arguments):n.queue.push(arguments)};if(!f._fbq)f._fbq=n;
        n.push=n;n.loaded=!0;n.version='2.0';n.queue=[];t=b.createElement(e);t.async=!0;
        t.src=v;s=b.getElementsByTagName(e)[0];s.parentNode.insertBefore(t,s)}(window,
        document,'script','https://connect.facebook.net/en_US/fbevents.js');

        fbq('init', '208927876160365');
        fbq('track', "PageView");</script>
        <noscript><img height="1" width="1" style="display:none"
        src="https://www.facebook.com/tr?id=208927876160365&ev=PageView&noscript=1"
        /></noscript>
        <!-- End Facebook Pixel Code -->
    </head>
    <body>

      <%# For Navigations %>
      <div>
        <%= render 'layouts/navigation_links' %>
      </div>

      <%# For Pages Content %>
      <div>
        <%= render 'layouts/messages' %>
         <%= yield %>
      </div>

      <%# Footer Content %>
      <footer>
        <%= render 'layouts/footer' %>
      </footer>

    </body>

    </html>