config/routes.rb
Rails.application.routes.draw do

  resources :associates

  resources "contacts", only: [:new, :create]

  resources :consultants

  get 'comments/create'

  get 'comments/destroy'

  resources :posts, :path => 'blog' do
    resources :comments
  end

  get 'whatwedo/starter'

  get 'whatwedo/agrinvest'

  get 'whatwedo/organic'

  get 'whatwedo/government'

  get 'careers/associate'

  get 'careers/independent'

  get 'whatwedo/social'

  get 'whatwedo/consulting'

  get 'whatwedo/technology'

  get 'home/index'

  get 'aboutus' => "home#aboutus"

  get 'whatwedo' => "home#whatwedo"

  get 'careers' => "home#careers"

  get 'starter' => "home#starter"

  get 'agrinvest' => "home#agrinvest"

  get 'gaae' => "home#gaae"

  get 'organic' => "home#organic"

  get 'privacy' => "home#privacy"

  get 'terms' => "home#terms"

  root 'home#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments

	has_attached_file :avatar, styles: { medium: "300x300>", show: "500x500>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

	has_attached_file :author, styles: { thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :author, content_type: /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "rendzina", password: "Rendz1na", only: :new
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to posts_url, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to posts_url, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :message, :avatar, :author, :author_name)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= simple_form_for @post, url: posts_path, html: { multipart: true } do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, input_html: { class: "form-control"} %>
    <%= f.input :message, input_html: { class: "form-control"} %>
    <%= f.file_field :avatar %>
    <hr>
    <%= f.input :author_name, input_html: { class: "form-control"} %>
    <%= f.file_field :author %>
  </div>
<br/>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success", style: "width: 30%" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3> Blog </h3>
          <span class="navs-social">
            <a href="#">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="#">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="#">
                <i class="fa fa-google-plus"></i>
            </a>
          </span>
            <br/><br/>
            <a href="/aboutus" class="link-design"><b> Read More <i class="fa fa-arrow-circle-down"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>
<div class="real-time-contact">
              <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
              <%= link_to root_path, class: 'send_enq' do %>
                 <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
              <% end %>
        </div>
<section class="content-section">

   <div class="container">

   </div>


         <div class="container">
           <center>
               <h3 class="design">The Business Reformer <br/><i class="fa fa-arrow-circle-o-down"></i></h3>
               <hr/>

           </center>


           <div class="col-md-3">
               <%= link_to whatwedo_social_path do %>
           <div class="circle-image">
              <%= image_tag "networking", width:"100%", style:"height: 100%" %>
           </div>
           <h4 class="design center"> Networking </h4>
           <% end %>

           <%= link_to whatwedo_consulting_path do %>
               <div class="circle-image">
                  <%= image_tag "IMG-20160510-WA0002", width:"100%", style:"height:100%" %>
               </div>
               <h4 class="design center"> Consulting </h4>
           <% end %>
           
           </div>
           <div class="col-md-6">
               <center><%= image_tag "blog", width: "60%" %> </center>
            <%= link_to new_post_path, class: "btn btn-success btn-lg" do %>
             <b><i class="fa fa-plus-circle"></i> New Post </b>
            <% end %>
           <% @posts.each do |post| %>
             <h4><%= link_to post.title, post %></h4>
             <% if post.avatar? %>
               <%= image_tag post.avatar.url(:medium) %>
             <% end %>
             <p><%= truncate post.message %></p>
               <p><%= image_tag post.author.url(:thumb) %>
               Written by: <%= post.author_name %></p>
             <p><%= time_ago_in_words post.created_at %> ago</p>
             <p><%= post.comments.count %> comments</p>
             <hr>
           <% end %>

          
         </div>
         <div class="col-md-3">
          <%= link_to whatwedo_organic_path do %>
           <div class="circle-image">
              <%= image_tag "organic_plan", width:"100%" %>
           </div>
           <h4 class="design center"> Organic Plan </h4>
           <% end %>

           <%= link_to whatwedo_technology_path do %>
               <div class="circle-image">
                  <%= image_tag "IMG-20160510-WA0005", width:"100%", style: "height: 100%" %>
               </div>
               <h4 class="design center"> Technology </h4>
           <% end %>
         </div>
         <Div class="clearfix"></div>
        </div>


    </div>
</section>


<section class="testimonies-section">

    <div class="container designer" >
          <div style="margin:50px auto;" class="container">
         <center>
             <h3 class="Google-font">Why Rendzina ? </h3>
        </center>
        <p class="justify">

         <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
         <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

        </p>

          </div>
     </div>
</section>

app/views/posts/new.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3>Our Blog </h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>

<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>
   <div class="container">
     <center>
         <h3 class="design">New Blog Post <br/><i class="fa fa-arrow-circle-down"></i></h3>
         <hr/>

     </center>

     <div class="col-md-4">
       <%= image_tag "blog", width: "80%" %>
      </div>
      <div class="col-md-6">
<%= render 'form' %>

<%= link_to 'Back', posts_path %>

</div>
<div class="clearfix"></div>
</div>
</section>


<section class="testimonies-section">

<div class="container designer" >
      <div style="margin:50px auto;" class="container">
     <center>
         <h3 class="Google-font">Why Rendzina ? </h3>
    </center>
    <p class="justify">

     <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
     <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

    </p>

      </div>
 </div>
</section>

app/views/posts/show.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3>Our Blog </h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>

<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>
   <div class="container">
     <center>
         <h3 class="design">Blog Post <br/><i class="fa fa-arrow-circle-down"></i></h3>
         <hr/>

     </center>

     <div class="col-md-4">
                   <%= image_tag "blog", width: "80%" %>
                </div>
                <div class="col-md-6">
<p><%= notice %></p>

    <h4 class="design"><%= @post.title %></h4>
    <% if @post.avatar? %>
      <%= image_tag @post.avatar.url(:show) %>
    <% end %>
    <p><%= @post.message %></p>

    <h4 class="design">Comments</h4>
    <hr>

      <%= @post.comments.each do |comment| %>
      	<p><%= comment.comment %></p>
      	<p><%= time_ago_in_words comment.created_at %> ago</p>
      	<p><%= link_to 'Delete Comment', [@post, comment], :method => :delete, :confirm => 'Are you sure?' %></p>
      	<hr>
      <% end %>


    <%= form_for [@post, @post.comments.build] do |f| %>
    	<p><%= f.text_area :comment, class: "form-control" %></p>
    	<p><%= f.submit "Post Comment", class: "btn btn-success", style: "width: 30%" %></p>
    <% end %>

<p>
<%= link_to 'Back', posts_path %>

</p>

</div>
<div class="clearfix"></div>
</section>


<section class="testimonies-section">

<div class="container designer" >
      <div style="margin:50px auto;" class="container">
     <center>
         <h3 class="Google-font">Why Rendzina ? </h3>
    </center>
    <p class="justify">

     <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
     <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

    </p>

      </div>
 </div>
</section>