config/routes.rb
Rails.application.routes.draw do

  resources :associates

  resources "contacts", only: [:new, :create]

  resources :consultants

  get 'comments/create'

  get 'comments/destroy'

  resources :posts, :path => 'blog' do
    resources :comments
  end

  get 'whatwedo/starter'

  get 'whatwedo/agrinvest'

  get 'whatwedo/organic'

  get 'whatwedo/government'

  get 'careers/associate'

  get 'careers/independent'

  get 'whatwedo/social'

  get 'whatwedo/consulting'

  get 'whatwedo/technology'

  get 'home/index'

  get 'aboutus' => "home#aboutus"

  get 'whatwedo' => "home#whatwedo"

  get 'careers' => "home#careers"

  get 'starter' => "home#starter"

  get 'agrinvest' => "home#agrinvest"

  get 'gaae' => "home#gaae"

  get 'organic' => "home#organic"

  get 'privacy' => "home#privacy"

  get 'terms' => "home#terms"

  root 'home#index'

end

app/models/associate.rb
class Associate < ActiveRecord::Base
end

app/controllers/associates_controller.rb
class AssociatesController < ApplicationController
  before_action :set_associate, only: [:show, :edit, :update, :destroy]

  # GET /associates
  # GET /associates.json
  def index
    @associates = Associate.all
  end

  # GET /associates/1
  # GET /associates/1.json
  def show
  end

  # GET /associates/new
  def new
    @associate = Associate.new
  end

  # GET /associates/1/edit
  def edit
  end

  # POST /associates
  # POST /associates.json
  def create
    @associate = Associate.new(associate_params)

    respond_to do |format|
      if @associate.save
        format.html { redirect_to root_path, notice: 'Associate was successfully created.' }
        format.json { render :show, status: :created, location: @associate }
      else
        format.html { render :new }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /associates/1
  # PATCH/PUT /associates/1.json
  def update
    respond_to do |format|
      if @associate.update(associate_params)
        format.html { redirect_to root_path, notice: 'Associate was successfully updated.' }
        format.json { render :show, status: :ok, location: @associate }
      else
        format.html { render :edit }
        format.json { render json: @associate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /associates/1
  # DELETE /associates/1.json
  def destroy
    @associate.destroy
    respond_to do |format|
      format.html { redirect_to associates_url, notice: 'Associate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_associate
      @associate = Associate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def associate_params
      params.require(:associate).permit(:surname, :other_names, :dob, :contact_add, :sec_institution, :sec_certificate, :sec_date, :uni_institution, :uni_certificate, :uni_date, :other_institution, :other_certificate, :other_date, :personal_statement, :hobbies, :telephone, :email)
    end
end

app/helpers/associates_helper.rb
module AssociatesHelper
end

app/views/associates/_form.html.erb
<%= simple_form_for(@associate) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :surname, input_html: { class: "form-control"} %>
    <%= f.input :other_names, input_html: { class: "form-control"} %>
    <%= f.input :dob , input_html:{ style: "padding: 10px;margin-top: 10px;width:30%"} %> <br/>
    <%= f.input :contact_add, input_html: { class: "form-control"} %>
    <%= f.input :sec_institution, input_html: { class: "form-control"} %>
    <%= f.input :sec_certificate, input_html: { class: "form-control"} %>

    <%= f.input :sec_date, input_html:{ style: "padding: 10px;margin-top: 10px;width:25%"} %> <br/>
    <%= f.input :uni_institution, input_html: { class: "form-control"} %>
    <%= f.input :uni_certificate, input_html: { class: "form-control"} %>
    <%= f.input :uni_date, input_html:{ style: "padding: 10px;margin-top: 10px;width:25%"} %><br/>
    <%= f.input :other_institution, input_html: { class: "form-control"} %>
    <%= f.input :other_certificate, input_html: { class: "form-control"} %>
    <%= f.input :other_date, input_html:{ style: "padding: 10px;margin-top: 10px;width:25%"} %><br/>
    <%= f.input :personal_statement, input_html: { class: "form-control"} %>
    <%= f.input :hobbies, input_html: { class: "form-control"} %>
    <%= f.input :telephone, input_html: { class: "form-control"} %>
    <%= f.input :email, input_html: { class: "form-control"} %>
  </div>
<br/>
  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-success", style: "width: 40%" %>
  </div>
<% end %>

app/views/associates/edit.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3>Careers</h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>

<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>
   <div class="col-md-6 col-md-offset-3">
     <center>
         <h3 class="design">Editing associate <br/><i class="fa fa-arrow-circle-down"></i></h3>
         <hr/>

     </center>


<%= render 'form' %>

<%= link_to 'Show', @associate %> |
<%= link_to 'Back', associates_path %>

</div>
<div class="clearfix"></div>
</section>


<section class="testimonies-section">

<div class="container designer" >
      <div style="margin:50px auto;" class="container">
     <center>
         <h3 class="Google-font">Why Rendzina ? </h3>
    </center>
    <p class="justify">

     <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
     <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

    </p>

      </div>
 </div>
</section>

app/views/associates/index.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3>Careers</h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>

<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>
   <div class="col-md-6 col-md-offset-3">
     <center>
         <h3 class="design">Listing associates <br/><i class="fa fa-arrow-circle-down"></i></h3>
         <hr/>

     </center>


<table class="table" style="background: #CCC;" cellpadding="5" cellspacing="1">
  <% @associates.each do |associate| %>
    <tr style="background: #ddd">
      <th>Surname</th>
        <td><%= associate.surname %></td>
    </tr>
    <tr  style="background: #FFF">
      <th>Other names</th>
        <td><%= associate.other_names %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Dob</th>
      <td><%= associate.dob %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Contact add</th>
      <td><%= associate.contact_add %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Sec institution</th>
      <td><%= associate.sec_institution %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Sec certificate</th>
      <td><%= associate.sec_certificate %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Sec date</th>
      <td><%= associate.sec_date %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Uni institution</th>
      <td><%= associate.uni_institution %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Uni certificate</th>
        <td><%= associate.uni_certificate %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Uni date</th>
      <td><%= associate.uni_date %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Other institution</th>
      <td><%= associate.other_institution %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Other certificate</th>
      <td><%= associate.other_certificate %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Other date</th>
      <td><%= associate.other_date %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Personal statement</th>
      <td><%= associate.personal_statement %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Hobbies</th>
    <td><%= associate.hobbies %></td>
  </tr>
  <tr style="background: #FFF">
      <th>Telephone</th>
    <td><%= associate.telephone %></td>
  </tr>
  <tr style="background: #ddd">
      <th>Email</th>
      <td><%= associate.email %></td>
    </tr>

      <tr>
        <td><%= link_to 'Click to Show', associate, style: "color: #000;font-weight:bold;" %></td>
        <td><%= link_to 'Edit', edit_associate_path(associate), style: "color: #000;font-weight:bold;" %> &nbsp; <%= link_to 'Destroy', associate, method: :delete, data: { confirm: 'Are you sure?' }, style: "color: #000;font-weight:bold;" %></td>

      </tr>
    <% end %>

</table>

<br>

<%= link_to  new_associate_path  do %>
  <b><i class="fa fa-edit"></i> New Associate</b>
<% end %>

</div>
<div class="clearfix"></div>
</section>


<section class="testimonies-section">

<div class="container designer" >
      <div style="margin:50px auto;" class="container">
     <center>
         <h3 class="Google-font">Why Rendzina ? </h3>
    </center>
    <p class="justify">

     <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
     <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

    </p>

      </div>
 </div>
</section>

app/views/associates/new.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3>Careers </h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>

<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>
   <div class="col-md-6 col-md-offset-3">
     <center>
         <h3 class="design">New associate <br/><i class="fa fa-arrow-circle-down"></i></h3>
         <hr/>

     </center>


<%= render 'form' %>

<%= link_to 'Back', associates_path %>
</div>
<div class="clearfix"></div>
</section>


<section class="testimonies-section">

<div class="container designer" >
      <div style="margin:50px auto;" class="container">
     <center>
         <h3 class="Google-font">Why Rendzina ? </h3>
    </center>
    <p class="justify">

     <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
     <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

    </p>

      </div>
 </div>
</section>

app/views/associates/show.html.erb
<section class="slider-section">
     <div class="image-placeholder">

        <div class="inner-text animated flipInX">
            <h3>Careers </h3>
          <span class="navs-social">
            <a href="<%= "http://facebook.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-facebook"></i>
            </a> &nbsp; &nbsp;
            <a href="<%= "http://twitter.com/rendzinaltd" %>" target="_blank">
                <i class="fa fa-twitter"></i>
            </a>
            &nbsp; &nbsp;
            <a href="<%= "https://www.linkedin.com/company/5143538?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A5143538%2Cidx%3A1-1-1%2CtarId%3A1461678678178%2Ctas%3ARendzina" %>" target="_blank">
                <i class="fa fa-linkedin"></i>
            </a>
          </span>
            <br/><br/>
            <a href="<%= aboutus_path %>" class="link-design"><b> Read More <i class="fa fa-arrow-circle-right"></i> </b></a> <br/> <br/>
        </div>
     </div>
    <div class="col-md-3">

    </div>
    <div class="clearfix"></div>
    <div style="height: 200px;">

    </div>
</section>

<section class="content-section">

   <div class="container">
     <div class="real-time-contact">
       <h4 class="design" style="padding:0px;margin:0px;"> Contact: </h4><i class="fa fa-phone"></i> <b>+234-90-54-66-0000</b><br/>
       <%= link_to root_path, class: 'send_enq' do %>
          <font class="color-green"><i class="fa fa-envelope-o"></i> Send Enquiry</font>
       <% end %>
     </div>
   </div>
   <div class="col-md-6 col-md-offset-3">
     <center>
         <h3 class="design">Listing associates <br/><i class="fa fa-arrow-circle-down"></i></h3>
         <hr/>

     </center>

<p id="notice"><%= notice %></p>

<table class="table" style="background: #CCC;" cellpadding="5" cellspacing="1">

    <tr style="background: #ddd">
      <th>Surname </th>
        <td>
          <%= @associate.surname %>
        </td>
    </tr>
    <tr  style="background: #FFF">
      <th>Other names</th>
        <td><%= @associate.other_names %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Dob</th>
      <td><%= @associate.dob %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Contact add</th>
      <td><%= @associate.contact_add %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Sec institution</th>
      <td><%= @associate.sec_institution %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Sec certificate</th>
      <td>  <%= @associate.sec_certificate %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Sec date</th>
      <td>  <%= @associate.sec_date %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Uni institution</th>
      <td>  <%= @associate.uni_institution %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Uni certificate</th>
        <td>  <%= @associate.uni_certificate %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Uni date</th>
      <td>  <%= @associate.uni_date %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Other institution</th>
      <td><%= @associate.other_institution %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Other certificate</th>
      <td>  <%= @associate.other_certificate %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Other date</th>
      <td>  <%= @associate.other_date %></td>
    </tr>
    <tr style="background: #FFF">
      <th>Personal statement</th>
      <td><%= @associate.personal_statement %></td>
    </tr>
    <tr style="background: #ddd">
      <th>Hobbies</th>
    <td>  <%= @associate.hobbies %></td>
  </tr>
  <tr style="background: #FFF">
      <th>Telephone</th>
    <td>  <%= @associate.telephone %></td>
  </tr>
  <tr style="background: #ddd">
      <th>Email</th>
      <td>  <%= @associate.email %></td>
    </tr>

      <tr>
        <td>
        <%= link_to 'Edit', edit_associate_path(@associate) %> |
        <%= link_to 'Back', associates_path %>
      </td>

      </tr>


</table>

<br>

<%= link_to  new_associate_path  do %>
  <b><i class="fa fa-edit"></i> New Associate</b>
<% end %>

</div>
<div class="clearfix"></div>
</section>


<section class="testimonies-section">

<div class="container designer" >
      <div style="margin:50px auto;" class="container">
     <center>
         <h3 class="Google-font">Why Rendzina ? </h3>
    </center>
    <p class="justify">

     <p> We are a team of young, energetic, responsive and intuitive thinkers in pursuit of revolutionary changes in our field of endeavor. We work closely with our clients to create the solutions they desire, that suit their intentions and exceed expectations. </p>
     <p>
Our theories and perspective of Management and Enterprise Development solutions are fashioned with the specifics of underdeveloped economic issues in mind, which makes us proactive in process, dynamic in delivery offering unscripted assistance to all. Our unique depth of insight spanning from an eclectic knowledge base, unquenchable passion for learning and a positive culture ensures we are the ones to speak to giving a voice to your aspirations. </p>
<p>
At Rendzina, we give a holistic approach to Enterprise development and project execution. We consider all the variable factors peculiar to our socio-economic environment to provide clients with bespoke solutions that meet their needs satisfactorily. </p>
<p>
We work closely with other organizations within and outside our sector to help provide a wide range of solutions outside our core discipline. We are not afraid to display original thinking and provocative in our novel solutions.
</p>

    </p>

      </div>
 </div>
</section>